title: NULL on error
tagline: flipping bits whilst updating pixels
url: https://nullonerror.org
baseurl: ""
permalink: pretty

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Rodrigo Delduca
  url: https://rodrigodelduca.org/
  email: rodrigodelduca@gmail.com

kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .git
  - .jekyll-cache
  - LICENSE.md
  - README.md
