name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Check health
        run: |
          curl "${SITE_URL}" && curl -fsS -m 10 --retry 5 -o /dev/null "https://hc-ping.com/${HEALTH_UUID}"
        env:
          HEALTH_UUID: ${{ secrets.HEALTH_UUID }}
          SITE_URL: ${{ secrets.SITE_URL }}
